# Site Settings
title: Dinesh
description: Taxonomist Transitioning to Data Management & Ontology
url: "https://rdinesh27.github.io"
baseurl: "/rdinesh27-jekyll"

# Personal Info
author:
  name: Dinesh R
  email: rdinesh27@protonmail.com
  bio: "Experienced Taxonomist evolving into Data Management and Ontology Engineering"

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Social Links
social:
  github: rdinesh27
  linkedin: your-linkedin-profile
  email: rdinesh27@protonmail.com